### ISSUE TITLE
Questions: KubeApplication annotation is mandatory, ...

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#17]
### KubernetesApplication mandatory

I must add the `@KubernetesApplication` in order to generate the resource files for the annotation `@CompositeAnnotation`. Can we avoid that @iocanel ?

### List of k8s 
Why do you generate a list of k8s's items for the Component @iocanel and not a Component object ?
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1beta1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: "fruit-client-sb"
  spec:
    deploymentMode: "innerloop"
    exposeService: false
    image: []
    env: []
    feature: []
    link: []
    service: []
``` 

### Not output the empty fields

Can we avoid to include within the generated resource files the empty fields ?
E.g : `image: []`,`labels: {}`
