### ISSUE TITLE
Populate K8s annotations for outerloop = s2i build - component operator

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#201]
## Feature request

Populate K8s annotations used by the Component Operator `prod = outerloop mode` according to what is discovered within the current maven project and git repo

For the moment, we hard code the info needed to perform a s2i build using ap4k k8s annotation

https://github.com/snowdrop/component-operator-demo/blob/master/fruit-backend-sb/src/main/java/com/example/demo/CrudApplication.java#L30-L39

```
@KubernetesApplication(
        annotations = {
                @Annotation(key = "app.openshift.io/artifact-copy-args", value = "*.jar"),
                @Annotation(key = "app.openshift.io/component-name", value = "fruit-backend-sb"),
                @Annotation(key = "app.openshift.io/git-dir", value = "fruit-backend-sb"),
                @Annotation(key = "app.openshift.io/git-ref", value = "master"),
                @Annotation(key = "app.openshift.io/git-uri", value = "https://github.com/snowdrop/component-operator-demo.git"),
                @Annotation(key = "app.openshift.io/java-app-jar", value = "fruit-backend-sb-0.0.1-SNAPSHOT.jar"),
                @Annotation(key = "app.openshift.io/runtime-image", value = "fruit-backend-sb")
        })
```
but most of the properties could be calculated dynamically by ap4k and added to the yaml/json file

```
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "component.k8s.io/v1alpha1"
  kind: "Component"
  metadata:
    annotations:
      app.openshift.io/java-app-jar: "fruit-backend-sb-0.0.1-SNAPSHOT.jar"
      app.openshift.io/artifact-copy-args: "*.jar"
      app.openshift.io/git-dir: "fruit-backend-sb"
      app.openshift.io/runtime-image: "fruit-backend-sb"
      app.openshift.io/git-ref: "master"
      app.openshift.io/component-name: "fruit-backend-sb"
      app.openshift.io/git-uri: "https://github.com/snowdrop/component-operator-demo.git"
    labels:
      app: "fruit-backend-sb"
      version: "0.0.1-SNAPSHOT"
      group: "dabou"
    name: "fruit-backend-sb"
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    version: "1.5.15.RELEASE"
...
```
