### ISSUE TITLE
Prevent dublicate resource.

### ISSUE THREAD

**Issue by iocanel** [ap4k/ap4k#28]
Currently, we heavily rely on visitor to perform any sort of config and model updates.

This is powerful, but if not carefull its possible to register a visitor twice leading to dublicate entries in the generated resources.

We need to prevent duplicates but also have a better way to track which visitor is registered from where.

**Comment by cmoulliard** [comment]
Can we close it @iocanel ?

**Comment by cmoulliard** [comment]
I still get some double resources

Example
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "component.k8s.io/v1alpha1"
  kind: "Component"
  metadata:
    name: ""
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: true
    env:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
```

Class
```
@CompositeApplication(
        exposeService = true,
        envVars = @Env(name = "SPRING_PROFILES_ACTIVE", value = "openshift-catalog"))
@ServiceCatalog(
   instances = @ServiceCatalogInstance(
        name = "postgresql-db",
        serviceClass = "dh-postgresql-apb",
        servicePlan = "dev",
        bindingSecret = "postgresql-db",
        parameters = {
                @Parameter(key = "postgresql_user", value = "luke"),
                @Parameter(key = "postgresql_password", value = "secret"),
                @Parameter(key = "postgresql_database", value = "my_data"),
                @Parameter(key = "postgresql_version", value = "9.6")
        }
   )
)
```

Any idea to resolve it ? @iocanel
