### ISSUE TITLE
Component CRD spec support ENV vars but not @CompositeAnnotation

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#39]
Component CRD spec support [ENV vars ](https://github.com/snowdrop/component-operator/blob/master/pkg/apis/component/v1alpha1/component_types.go#L51)but not `@CompositeAnnotation`. Even if we specify such info
```
@CompositeApplication(envVars = @Env(name = "key1", value = "val1"))
```
the yaml file generated is empty
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1beta1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: "component-example"
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: false
    image: []
    env: []
    feature: []
    link: []
    service: []
```
