### ISSUE TITLE
Runtime's field is empty if we generate enVARs

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#42]
### Steps to reproduce

Do `mvn compile` of the [component-example ](https://github.com/ap4k/ap4k/blob/master/examples/component-example/src/main/java/io/ap4k/examples/component/Main.java)project

```
package io.ap4k.examples.component;

import io.ap4k.annotation.Env;
import io.ap4k.annotation.KubernetesApplication;
import io.ap4k.component.annotation.CompositeApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@KubernetesApplication
@CompositeApplication(envVars = @Env(name = "key1", value = "val1"))
@SpringBootApplication
public class Main {

  public static void main(String[] args) {
    SpringApplication.run(Main.class, args);
  }

}
```

### File generated

As you can see the file generated contains the envVar but runtime's field is empty
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1beta1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: "component-example"
  spec:
    deploymentMode: "innerloop"
    exposeService: false
    image: []
    env:
    - name: "key1"
      value: "val1"
    - name: "key1"
      value: "val1"
    feature: []
    link: []
    service: []
```
