### ISSUE TITLE
Wrong ApiVersion version added

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#46]
### Description of the issue

When we generate the resource for a `Component`, then the apiVersion included is `apiVersion: "v1beta1"` and not  the `apiVersion` of the CRD which is here `component.k8s.io/v1alpha1`

### Generated

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1beta1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: ""
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: false
    image: []
    env:
    - name: "key1"
      value: "val1"
    - name: "key1"
      value: "val1"
    feature: []
    link: []
    service: []
```
