### ISSUE TITLE
exposeService value is always equal to false

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#47]
### Description of the issue

The `exposeService` spec field value is always equal to `false` even if we set to tru within the annotation

```
@CompositeApplication(name = "hello-spring-boot", exposeService = true)
```

### Generated File
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1beta1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: "hello-spring-boot"
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: false
    image: []
    env: []
    feature: []
    link: []
    service: []
```
