### ISSUE TITLE
No parameter added to the yaml file generated

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#54]
### GAVs used
```
        <!-- To generate CRD -->
        <dependency>
            <groupId>io.ap4k</groupId>
            <artifactId>ap4k-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.ap4k</groupId>
            <artifactId>component-annotations</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.ap4k</groupId>
            <artifactId>servicecatalog-annotations</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.ap4k</groupId>
            <artifactId>ap4k-spring-boot</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
```

### Description

The following java class annotated using `@ServiceCatalog, @ServiceInstances and @Parameter` doesn' t include within the generated yml file the parameters

```
package com.example.demo;

import io.ap4k.component.annotation.CompositeApplication;
import io.ap4k.kubernetes.annotation.Env;
import io.ap4k.servicecatalog.annotation.Parameter;
import io.ap4k.servicecatalog.annotation.ServiceCatalog;
import io.ap4k.servicecatalog.annotation.ServiceCatalogInstance;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@CompositeApplication(
        exposeService = true, 
        envVars = @Env(name = "SPRING_PROFILES_ACTIVE", value = "openshift-catalog"))
@ServiceCatalog(
   instances = @ServiceCatalogInstance(
        name = "postgresql-db",
        serviceClass = "dh-postgresql-apb",
        servicePlan = "dev",
        bindingSecret = "postgresql-db",
        parameters = {
                @Parameter(key = "postgresql_user", value = "luke"),
                @Parameter(key = "postgresql_password", value = "secret"),
                @Parameter(key = "postgresql_database", value = "my_data"),
                @Parameter(key = "postgresql_version", value = "9.6")
        }
   )
)
```

### Yaml file generated

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "component.k8s.io/v1alpha1"
  kind: "Component"
  metadata:
    annotations: {}
    labels: {}
    name: ""
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: true
    image: []
    env:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
    feature: []
    link: []
    service:
    - name: "postgresql-db"
      class: "dh-postgresql-apb"
      plan: "dev"
      secretName: "postgresql-db"
      parameters: []

```
