### ISSUE TITLE
Link - Env annotation appears twice within yaml generated

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#65]
### Class annotated

```
@SpringBootApplication
@CompositeApplication(
        name = "fruit-client-sb",
        links = @Link(
                  name = "Env var to be injected within the target component -> fruit-backend",
                  targetcomponentname = "fruit-client-sb",
                  kind = "Env",
                  ref = "",
                  envVars = @Env(
                          name  = "OPENSHIFT_ENDPOINT_BACKEND",
                          value = " http://fruit-backend-sb:8080/api/fruits"
                  )
))
```

### Yaml generated
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "component.k8s.io/v1alpha1"
  kind: "Component"
  metadata:
    name: "fruit-client-sb"
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: false
    link:
    - kind: "Env"
      name: "Env var to be injected within the target component -> fruit-backend"
      targetComponentName: "fruit-client-sb"
      envs:
      - name: "OPENSHIFT_ENDPOINT_BACKEND"
        value: " http://fruit-backend-sb:8080/api/fruits"
      ref: ""
    - kind: "Env"
      name: "Env var to be injected within the target component -> fruit-backend"
      targetComponentName: "fruit-client-sb"
      envs:
      - name: "OPENSHIFT_ENDPOINT_BACKEND"
        value: " http://fruit-backend-sb:8080/api/fruits"
      ref: ""
```

Same issue too using this config (see double Envs and double Vars)
```
@CompositeApplication(
        name = "fruit-backend-sb",
        exposeService = true,
        envVars = @Env(
                name = "SPRING_PROFILES_ACTIVE",
                value = "openshift-catalog"),
        links = @Link(
                name = "Secret to be injected as EnvVar using Service's secret",
                targetcomponentname = "fruit-backend-sb",
                kind = "Secret",
                ref = "postgresql-db"))
@ServiceCatalog(
   instances = @ServiceCatalogInstance(
        name = "postgresql-db",
        serviceClass = "dh-postgresql-apb",
        servicePlan = "dev",
        bindingSecret = "postgresql-db",
        parameters = {
                @Parameter(key = "postgresql_user", value = "luke"),
                @Parameter(key = "postgresql_password", value = "secret"),
                @Parameter(key = "postgresql_database", value = "my_data"),
                @Parameter(key = "postgresql_version", value = "9.6")
        }
   )
)
```

Result
```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "component.k8s.io/v1alpha1"
  kind: "Component"
  metadata:
    name: "fruit-backend-sb"
  spec:
    deploymentMode: "innerloop"
    runtime: "spring-boot"
    exposeService: true
    env:
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
    - name: "SPRING_PROFILES_ACTIVE"
      value: "openshift-catalog"
    link:
    - kind: "Secret"
      name: "Secret to be injected as EnvVar using Service's secret"
      targetComponentName: "fruit-backend-sb"
      ref: "postgresql-db"
    - kind: "Secret"
      name: "Secret to be injected as EnvVar using Service's secret"
      targetComponentName: "fruit-backend-sb"
      ref: "postgresql-db"
```
